name: 'Create UnityPackage'
description: 'Create a .unitypackage file from a Unity project'
author: 'AndanteTribe'
inputs:
  package-path:
    description: 'Output unitypackage file path'
    required: true
  include-files:
    description: 'Relative file paths from project-folder. Multi-line string value. Each line should end with .meta.'
    required: true
  project-folder:
    description: 'Unity project folder. Default => ./'
    required: false
  working-folder:
    description: 'The working folder where this Node.js script runs.'
    required: false
runs:
  using: 'composite'
  steps:
    # see: https://github.com/pCYSl5EDgo/create-unitypackage
    - uses: pCYSl5EDgo/create-unitypackage@b5c57408698b1fab8b3a84d4b67f767b8b7c0be9 # v1.2.3
      with:
        package-path: ${{ inputs.package-path }}
        include-files: ${{ inputs.include-files }}
        project-folder: ${{ inputs.project-folder }}
        working-folder: ${{ inputs.working-folder }}
