name: 'Unity Cache'
description: 'Unity Project Cache Control Wrapper.'
author: 'AndanteTribe'
inputs:
  unity-project-path:
    description: 'A directory paths for the Unity project to be cached and restored.'
    required: true
  upload-chunk-size:
    description: 'The chunk size used to split up large files during upload, in bytes. Self-hosted runners are ignored.'
    required: false
  fail-on-cache-miss:
    description: 'Fail the workflow if cache entry is not found.'
    default: 'false'
    required: false
  lookup-only:
    description: 'Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache.'
    default: 'false'
    required: false
  use-nugetforunity:
    description: 'Supports cache resolution and cache management via NuGetForUnity.Cli in Unity projects using NuGetForUnity.'
    default: 'false'
    required: false
  nuget-packages-path:
    description: 'A directory path where NuGetForUnity downloads packages. Used when use-nugetforunity is true.'
    required: false
  local-cashe-path:
    description: 'A directory path to store cache locally on self-hosted runners.'
    default: 'cache'
    required: false

outputs:
  cache-hit-unity:
    description: 'A boolean value indicating that the cache for the target Unity project has been found.'
    value: ${{ steps.unity-cache.outputs.cache-hit == 'true' || steps.unity-cache-local.outputs.cache-hit == 'true' }}
  cache-hit-nuget:
    description: 'A boolean value indicating that the NuGet cache for the target Unity project has been found.'
    value: ${{ steps.nuget-cache.outputs.cache-hit == 'true' || steps.nuget-cache-local.outputs.cache-hit == 'true' }}
runs:
  using: "composite"
  steps:
    - name: Fetch unity project info
      id: info
      uses: AndanteTribe/Actions/actions/fetch-unity-info@main
      with:
        unity-project-path: ${{ inputs.unity-project-path }}

#    - name: Fetch unity project info (Fallback)
#      id: info
#      shell: bash
#      run: |
#        # Unityのバージョンファイルとパッケージリストのハッシュを組み合わせて一意のキーを作る
#        CACHE_KEY="${{ runner.os }}-${{ hashFiles(format('{0}/ProjectSettings/ProjectVersion.txt', inputs.unity-project-path), format('{0}/Packages/manifest.json', inputs.unity-project-path)) }}"
#            echo "name=${CACHE_KEY}" >> $GITHUB_OUTPUT

    - name: Setup local cache Directory
      if: ${{ contains(runner.labels, 'self-hosted') }}
      shell: bash
      run: |
        mkdir -p "${{ inputs.local-cashe-path }}"
        echo "*" > "${{ inputs.local-cashe-path }}/.gitignore"

    - name: Restore nuget cache (Local)
      if: ${{ inputs.use-nugetforunity == 'true' && !contains(runner.labels, 'self-hosted') }}
      id: nuget-cache-local
      shell: bash
      run: |
          CACHE_DIR="${{ inputs.local-cache-path }}/nuget-${{ steps.info.outputs.name }}"
          TARGET_DIR="${{ inputs.nuget-packages-path }}"
          if [ -d "$CACHE_DIR" ] && [ "$(ls -A "$CACHE_DIR")" ]; then
            echo "Local Unity cache found."
            echo "cache-hit=true" >> $GITHUB_OUTPUT
            mkdir -p "$TARGET_DIR"
            cp -a "$CACHE_DIR/." "$TARGET_DIR/"
          else
            echo "Local Unity cache not found."
            echo "cache-hit=false" >> $GITHUB_OUTPUT
          fi

    - name: Restore nuget cache (Cloud)
      if: ${{ inputs.use-nugetforunity == 'true' && !contains(runner.labels, 'self-hosted') }}
      id: nuget-cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.nuget-packages-path }}
        key: nuget-cache-${{ steps.info.outputs.name }}
        upload-chunk-size: ${{ inputs.upload-chunk-size }}
        fail-on-cache-miss: ${{ inputs.fail-on-cache-miss }}
        lookup-only: ${{ inputs.lookup-only }}

    - name: Run NuGetForUnity restore
      if: ${{ inputs.use-nugetforunity == 'true' && steps.nuget-cache.outputs.cache-hit != 'true' && steps.nuget-cache-local.outputs.cache-hit != 'true'}}
      uses: AndanteTribe/Actions/actions/nugetforunity-restore@main
      with:
        unity-project-path: ${{ inputs.unity-project-path }}
        nuget-packages-path: ${{ inputs.nuget-packages-path }}

    - name: Restore unity project cache (Cloud)
      if: ${{ !contains(runner.labels, 'self-hosted') }}
      id: unity-cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.unity-project-path }}/Library
        key: unity-cache-${{ steps.info.outputs.name }}
        upload-chunk-size: ${{ inputs.upload-chunk-size }}
        fail-on-cache-miss: ${{ inputs.fail-on-cache-miss }}
        lookup-only: ${{ inputs.lookup-only }}

    - name: Restore unity project cache (Local)
      if: ${{ contains(runner.labels, 'self-hosted') }}
      id: unity-cache-local
      shell: bash
      run: |
          CACHE_DIR="${{ inputs.local-cache-path }}/unity-${{ steps.info.outputs.name }}"
          TARGET_DIR="${{ inputs.unity-project-path }}/Library"
          if [ -d "$CACHE_DIR" ] && [ "$(ls -A "$CACHE_DIR")" ]; then
            echo "Local Unity cache found."
            echo "cache-hit=true" >> $GITHUB_OUTPUT
            mkdir -p "$TARGET_DIR"
            cp -a "$CACHE_DIR/." "$TARGET_DIR/"
          else
            echo "Local Unity cache not found."
            echo "cache-hit=false" >> $GITHUB_OUTPUT
          fi

    - name: Save local unity project cache
      if: ${{ contains(runner.labels, 'self-hosted') && always()}}
      shell: bash
      run: |
          CACHE_DIR="cache/unity-${{ steps.info.outputs.name }}"
          TARGET_DIR="${{ inputs.unity-project-path }}/Library"
          mkdir -p "$CACHE_DIR"
          cp -a "$TARGET_DIR/." "$CACHE_DIR/"