name: 'Fetch Unity Project Info'
description: 'Fetches Unity project information and writes it to GITHUB_OUTPUT.'
inputs:
  unity-project-path:
    description: 'A directory path for the Unity project.'
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    UNITY_PROJECT_PATH: ${{ inputs.unity-project-path }}
  args:
    - share/FetchUnityProjectInfo.cs
