name: 'Fetch Unity Project Info'
description: 'Fetch Unity project name from project path and write to GITHUB_OUTPUT.'
inputs:
  unity-project-path:
    description: 'A directory path for the Unity project.'
    required: true
outputs:
  name:
    description: 'The Unity project directory name.'
    value: ${{ steps.fetch.outputs.name }}
runs:
  using: composite
  steps:
    - name: Fetch project name
      id: fetch
      shell: bash
      env:
        UNITY_PROJECT_PATH: ${{ inputs.unity-project-path }}
      run: |
        name=$(basename "$UNITY_PROJECT_PATH")
        echo "name=$name" >> "$GITHUB_OUTPUT"
