FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app

RUN dotnet tool install --global NuGetForUnity.Cli
ENV PATH="${PATH}:/root/.dotnet/tools"

COPY cache/nugetforunity-restore.sh .
RUN chmod +x nugetforunity-restore.sh

ENTRYPOINT ["/app/nugetforunity-restore.sh"]
