FROM mcr.microsoft.com/dotnet/sdk:9.0

ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global NuGetForUnity.Cli

ARG UNITY_PROJECT_PATH
COPY . ${UNITY_PROJECT_PATH}
ENTRYPOINT ["nugetforunity", "restore"]
