FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /work

ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global NuGetForUnity.Cli

COPY ${UNITY_PROJECT_PATH}  . 
ENTRYPOINT ["nugetforunity", "restore"]
