name: 'Static Analysis'

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      # see: https://github.com/AndanteTribe/Actions/tree/main/actions/checkout
      - uses: AndanteTribe/Actions/actions/checkout@main
        with:
          persist-credentials: false
      - uses: ./actions/static-analysis
        with:
          token: ${{ github.token }}
