name: 'Static Analysis'

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      # see: https://github.com/actions/checkout
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      # see: https://github.com/AndanteTribe/Actions/tree/main/actions/static-analysis
      - uses: ./actions/static-analysis
        with:
          token: ${{ github.token }}
